### ISSUE TITLE
conv_single_step()函数实现有问题（第4门课程《卷积神经网络》第一次作业Convolution Model-Step by Step）

### ISSUE THREAD

**Issue by Lanyu123** [eplt/deep-learning-coursera-complete#1]
函数conv_single_step()实现中：

应该是 W*X 先求和，在加偏置b，而不是每一个wi * xi 都加一个b

    # START CODE HERE ### (≈ 2 lines of code)
    # Element-wise product between a_slice and W. Do not add the bias yet.
    s = a_slice_prev * W
    # Sum over all entries of the volume s.
    Z = np.sum(s)
    # Add bias b to Z. Cast b to a float() so that Z results in a scalar value.
    Z = Z + float(b)
    # ## END CODE HERE ###
这样应该才对

**Comment by eplt** [comment]
fixed.
